### ISSUE TITLE
Popups triggered by overpass turbo map

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/learnoverpass#3]
I tried to change some of the Overpass QL code snippets in the reference section, but each time I do any change, a popup with syntax errors appears. Also, I noticed that when switching from one reference page to another reference page, I also sometimes get some intermediate popups.

**Comment by Secretmapper** [comment]
Currently creating a JS API for the interactive map that should fix this!

**Comment by Secretmapper** [comment]
Fixed by ccdbb3a4a4b1e8a369a9cad5726a7d8343198d2f!

**Comment by mmd-osm** [comment]
Cool. The popups are gone. On Firefox console/Firebug I get some error messages. It's probably not a big thing, maybe you've already seen this:

![s1](https://cloud.githubusercontent.com/assets/5842757/8475481/876c25b8-20b8-11e5-9b5b-67460a76d78d.png)

**Comment by tyrasd** [comment]
+1 for delaying query execution a bit and to call kill_my_queries even if it's currently buggy.

**Comment by Secretmapper** [comment]
Yup, right now it's being console logged as I'm planning on a way to show the errors.

The query is being delayed by _200 Millisecond_, which I agree is very low. Another code-run website that uses 'autocompile' (Codecombat) use a 5 second delay, so I guess we can delay that long and we can tweak it to what works best for the project :)
