### ISSUE TITLE
Typo in lesson 15

### ISSUE THREAD

**Issue by wireguy** [osmlab/learnoverpass#34]
Lesson 15 has the misspelled word 'reemove'

**Comment by Dartanjan** [comment]
Also the way has a different name, should be:

`way["addr:city"=Passau][name="Wirtschaftswissenschaften (WIWI)"];`

instead of just `Wirtschaftswissenschaften`.

**Comment by irnc** [comment]
Thanks for reporting @wireguy and @Dartanjan! Both issues were fixed by @KristjanESPERANTO in #35 and #36.
