### ISSUE TITLE
Recurse down when already on node level

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/learnoverpass#7]
I noticed the following query in http://osmlab.github.io/learnoverpass/en/docs/filters/polygon/

```
(node(poly:"50.73 7.13 50.73 7.17 50.75 7.15");>;);
out;
```

As we're already on node level, the additional `>;` has no effect. You probably intended this to be a template for ways/rels as well. In that case, I would just put the other options as comment, maybe.

Example:

```
node(poly:"50.73 7.13 50.73 7.17 50.75 7.15");
//
// (way(poly:"50.73 7.13 50.73 7.17 50.75 7.15");>;);
out;
```

**Comment by Secretmapper** [comment]
Yup, this was meant as a template so that node can easily be replaced by way/relation.

Admittedly though it doesn't really scale as the way output only has a vague triangle with a large protruding way. There should be indeed a better way to do this now though with the multiple sample support :)
