### ISSUE TITLE
Hardcoded answer in exercises 

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/learnoverpass#9]
Somehow I'm not sure if including concrete Overpass API results in exercise files is a good idea. Tomorrow, someone might add another language to that POI or more it around -> string comparison no longer works. To me this seems rather fragile, given the highly dynamic and volatile nature of OSM data.

At the end of the day you really want to check, if the Overpass API request is correct. So either normalize the query (=remove comments, white spaces, etc.) before comparing them or maybe fire a second predefined query and compare those results with what the user got with his query.

**Comment by Secretmapper** [comment]
Very nice point :) I think that the second predefined query is way better and less fragile.

**Comment by tyrasd** [comment]
@Secretmapper haven't you implemented that already?

**Comment by Secretmapper** [comment]
@tyrasd The queries/results are being normalized, but the answers themselves were hardcoded. I've issued a commit (and PR for turbo) to use @mmd-osm's solution

**Comment by tyrasd** [comment]
> and PR for turbo

merged
